apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: portfolio-custom-tls
  namespace: labs
spec:
  secretName: portfolio-custom-tls
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
  dnsNames:
      - preview.dmitriimashkov.com
      - dmitriimashkov.com
