# Tenant configuration for: my-team
# Created by: wft-create-tenant workflow
# Managed by: ArgoCD ApplicationSet (applicationset-tenants)
tenant:
  name: my-team
  displayName: "my-team"
  description: ""
  contactEmail: ""
  members:
    - userId: mctl-reviewer
      role: owner
  quotas:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "6"
    limits.memory: "12Gi"
    pods: "10"
    persistentvolumeclaims: "5"
    services: "10"
  limitRange:
    enabled: true
    default:
      cpu: "500m"
      memory: "1Gi"
    defaultRequest:
      cpu: "200m"
      memory: "512Mi"
    max:
      cpu: "2"
      memory: "4Gi"
  networking:
    allowIntraNamespace: true
    allowClusterEgress: true
    allowInternetEgress: true
