apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tenant-labs
  namespace: default
  description: "Tenant labs — namespace, quotas, and network policies"
  annotations:
    mctl.me/tenant-name: "labs"
    backstage.io/managed-by-location: "url:https://github.com/mctlhq/mctl-gitops/blob/main/platform-gitops/tenants/labs/catalog-info.yaml"
    backstage.io/managed-by-origin-location: "url:https://github.com/mctlhq/mctl-gitops/blob/main/platform-gitops/tenants/labs/catalog-info.yaml"
spec:
  type: tenant
  owner: group:default/admins
  system: team-labs
  dependsOn: []
