apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tenant-mashkoffdmitry
  namespace: default
  description: "Tenant mashkoffdmitry — namespace, quotas, and network policies"
  annotations:
    mctl.me/tenant-name: "mashkoffdmitry"
    backstage.io/managed-by-location: "url:https://github.com/mctlhq/mctl-core/blob/main/platform-gitops/tenants/mashkoffdmitry/catalog-info.yaml"
    backstage.io/managed-by-origin-location: "url:https://github.com/mctlhq/mctl-core/blob/main/platform-gitops/tenants/mashkoffdmitry/catalog-info.yaml"
spec:
  type: tenant
  owner: group:default/admins
  system: team-mashkoffdmitry
  dependsOn: []
