{{- if .Values.registryCredentials }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "base-service.fullname" . }}-registry
  labels:
    {{- include "base-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.registryCredentials.refreshInterval | default "24h" }}
  secretStoreRef:
    name: {{ .Values.registryCredentials.store | default "vault-backend" }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.registryCredentials.secretName | default (printf "%s-registry" (include "base-service.fullname" .)) }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ "{{ .dockerconfigjson }}" }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: {{ .Values.registryCredentials.vaultKey }}
        property: dockerconfigjson
{{- end }}
