{{- range $name, $es := .Values.extraExternalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  labels:
    {{- include "base-service.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $es.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $es.store | default "vault-backend" }}
    kind: ClusterSecretStore
  target:
    name: {{ $es.targetSecret | default $name }}
    creationPolicy: Owner
    {{- if or $es.targetTemplateType $es.targetTemplateMetadataAnnotations }}
    template:
      {{- if $es.targetTemplateType }}
      type: {{ $es.targetTemplateType }}
      {{- end }}
      {{- if $es.targetTemplateMetadataAnnotations }}
      metadata:
        annotations:
          {{- range $k, $v := $es.targetTemplateMetadataAnnotations }}
          {{ $k }}: {{ $v | quote }}
          {{- end }}
      {{- end }}
    {{- end }}
  data:
    {{- range $es.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        property: {{ .property }}
    {{- end }}
{{- end }}
