{
 "title": "Kubernetes / Views / Global",
 "description": "This is a modern 'Global View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus",
  "vm-k8s-stack"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": ".*" },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   { "name": "job", "query": "node-exporter" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(instance,cpu,cluster)) by(cluster)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",cluster=~\"$cluster\"} and on(namespace,pod,cluster) max(kube_pod_status_phase{phase=\"Running\",cluster=~\"$cluster\"} == 1) by(namespace,pod,cluster)) by(cluster) / sum(machine_cpu_cores{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",cluster=~\"$cluster\"} and on(namespace,pod,cluster) max(kube_pod_status_phase{phase=\"Running\",cluster=~\"$cluster\"} == 1) by(namespace,pod,cluster)) by(cluster) / sum(machine_cpu_cores{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"$job\"} - node_memory_MemAvailable_bytes{cluster=~\"$cluster\",job=\"$job\"}) by(cluster) / sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"$job\"}) by(cluster)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",cluster=~\"$cluster\"} and on(namespace,pod,cluster) max(kube_pod_status_phase{phase=\"Running\",cluster=~\"$cluster\"} == 1) by(namespace,pod,cluster)) by(cluster) / sum(machine_memory_bytes{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",cluster=~\"$cluster\"} and on(namespace,pod,cluster) max(kube_pod_status_phase{phase=\"Running\",cluster=~\"$cluster\"} == 1) by(namespace,pod,cluster)) by(cluster) / sum(machine_memory_bytes{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(kube_node_info{cluster=~\"$cluster\"}) by(node,cluster)) by(cluster)"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_pod_container_status_running{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\",cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_endpoint_info{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(kube_ingress_info{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(count(kube_node_info{cluster=~\"$cluster\"}) by(node,cluster)) by(cluster)",
     "legendFormat": "Nodes"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_namespace_created{cluster=~\"$cluster\"}) by(cluster)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(cluster)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",cluster=~\"$cluster\"} and on(namespace,pod,cluster) max(kube_pod_status_phase{phase=\"Running\",cluster=~\"$cluster\"} == 1) by(namespace,pod,cluster)) by(cluster)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",cluster=~\"$cluster\"} and on(namespace,pod,cluster) max(kube_pod_status_phase{phase=\"Running\",cluster=~\"$cluster\"} == 1) by(namespace,pod,cluster)) by(cluster)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_cpu_cores{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"$job\"} - node_memory_MemAvailable_bytes{cluster=~\"$cluster\",job=\"$job\"}) by(cluster)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\",cluster=~\"$cluster\"} and on(namespace,pod,cluster) max(kube_pod_status_phase{phase=\"Running\",cluster=~\"$cluster\"} == 1) by(namespace,pod,cluster)) by(cluster)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\",cluster=~\"$cluster\"} and on(namespace,pod,cluster) max(kube_pod_status_phase{phase=\"Running\",cluster=~\"$cluster\"} == 1) by(namespace,pod,cluster)) by(cluster)",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_memory_bytes{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\",cluster=~\"$cluster\"}) by(cluster)"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(instance,cpu,cluster)) by(cluster)",
     "legendFormat": "CPU usage in %"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"$job\"} - node_memory_MemAvailable_bytes{cluster=~\"$cluster\",job=\"$job\"}) by(cluster) / sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"$job\"}) by(cluster)",
     "legendFormat": "Memory usage in %"
    }
   ]
  },
  {
   "title": "CPU Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",cluster=~\"$cluster\"}[$__rate_interval])) by(namespace,cluster)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",cluster=~\"$cluster\"}) by(namespace,cluster)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\",cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(instance,cpu,cluster)) by(instance,cluster)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Memory Utilization by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=~\"$cluster\",job=\"$job\"} - node_memory_MemAvailable_bytes{cluster=~\"$cluster\",job=\"$job\"}) by(instance,cluster)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Throttled seconds by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{image!=\"\",cluster=~\"$cluster\"}[$__rate_interval])) by(namespace,cluster) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "CPU Core Throttled by instance",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_core_throttles_total{cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(instance,cluster)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Kubernetes Pods QoS classes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_qos_class{cluster=~\"$cluster\"}) by(qos_class,cluster)",
     "legendFormat": "{{ qos_class }} pods"
    },
    {
     "expr": "sum(kube_pod_info{cluster=~\"$cluster\"}) by(cluster)",
     "legendFormat": "Total pods"
    }
   ]
  },
  {
   "title": "Kubernetes Pods Status Reason",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_reason{cluster=~\"$cluster\"}) by(reason,cluster)",
     "legendFormat": "{{ reason }}"
    }
   ]
  },
  {
   "title": "OOM Events by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(container_oom_events_total{cluster=~\"$cluster\"}[$__rate_interval])) by(namespace,cluster) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Container Restarts by namespace",
   "type": "timeseries",
   "description": "No data is generally a good thing here.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{cluster=~\"$cluster\"}[$__rate_interval])) by(namespace,cluster) > 0",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Global Network Utilization by device",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc).*\",cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(device,cluster)",
     "legendFormat": "Received : {{ device }}"
    },
    {
     "expr": "0 - sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc).*\",cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(device,cluster)",
     "legendFormat": "Transmitted : {{ device }}"
    }
   ]
  },
  {
   "title": "Network Saturation - Packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_drop_total{cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(cluster)",
     "legendFormat": "Packets dropped (receive)"
    },
    {
     "expr": "0 - sum(rate(node_network_transmit_drop_total{cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(cluster)",
     "legendFormat": "Packets dropped (transmit)"
    }
   ]
  },
  {
   "title": "Network Received by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{cluster=~\"$cluster\"}[$__rate_interval])) by(namespace,cluster)",
     "legendFormat": "Received : {{ namespace }}"
    },
    {
     "expr": "0 - sum(rate(container_network_transmit_bytes_total{cluster=~\"$cluster\"}[$__rate_interval])) by(namespace,cluster)",
     "legendFormat": "Transmitted : {{ namespace }}"
    }
   ]
  },
  {
   "title": "Total Network Received (with all virtual devices) by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(instance,cluster)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "0 - sum(rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(instance,cluster)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  },
  {
   "title": "Network Received (without loopback)  by instance",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"(veth|azv|lxc|lo).*\",cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(instance,cluster)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "0 - sum(rate(node_network_transmit_bytes_total{device!~\"(veth|azv|lxc|lo).*\",cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(instance,cluster)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  },
  {
   "title": "Network Received (loopback only) by instance",
   "type": "timeseries",
   "description": "Dropped noisy virtual devices for readability.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=\"lo\",cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(instance,cluster)",
     "legendFormat": "Received bytes in {{ instance }}"
    },
    {
     "expr": "0 - sum(rate(node_network_transmit_bytes_total{device=\"lo\",cluster=~\"$cluster\",job=\"$job\"}[$__rate_interval])) by(instance,cluster)",
     "legendFormat": "Transmitted bytes in {{ instance }}"
    }
   ]
  }
 ]
}