# Service: knot-mvp
# Team: mashkoffdmitry

# Chart: base-service

image:
  repository: ghcr.io/mctlhq/knot-mvp
  tag: "1.2.1"
imagePullSecrets:
  - name: ghcr-credentials
service:
  port: 5006
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  APP_ENV: production
  NODE_ENV: production
  JWT_SECRET: 2e11a5c56c6cd381112209265f9add52695b881f08617ea4d80dae5e905e42b2
ingress:
  enabled: true
  hosts:
    - mashkoffdmitry-knot-mvp.mctl.ai
    - mashkoffdmitry-knot-mvp.mctl.me
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: knot-mvp-tls
      hosts:
        - mashkoffdmitry-knot-mvp.mctl.ai
        - mashkoffdmitry-knot-mvp.mctl.me
dbSecret:
  vaultPath: "teams/mashkoffdmitry/knot-mvp/database"
  secretName: "mashkoffdmitry-knot-mvp-db-creds"
envFrom:
  - secretRef:
      name: "mashkoffdmitry-knot-mvp-db-creds"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
