image:
  repository: ghcr.io/dmitriimashkov/test-delete-service
  tag: "latest"

service:
  port: 8080

ingress:
  enabled: true
  host: test-delete.preview.mctl.me

replicas: 1

env:
  - name: APP_NAME
    value: "test-delete-service"

secretRef: test-delete-service-secrets
