# ZITADEL (auth.mctl.ai) as a Cloudflare Access identity provider (#1500 step 3).
#
# Added NEXT TO the existing providers. No existing application's
# allowed_idps or policy changes here; the only application that offers it
# is the throwaway test application below, until the owner's test login
# succeeds and #1329's probe watches it.
#
# The ZITADEL side is a public client with PKCE (zitadel-iac
# iac/cloudflare-access.tf): OIDC_AUTH_METHOD_TYPE_NONE, so there is no client
# secret to carry from the cluster into this root. Verified on a local
# ZITADEL v4.19.2: the token endpoint requires a valid S256 code_verifier and
# ignores any client secret sent, and a user without a grant on the
# `Cloudflare Access` project is refused before Access sees them.
#
# client_secret is a fixed placeholder, not a credential. Both schemas mark
# it optional, but the API requires it for type oidc: the first apply
# (run 37193959324, 2026-10-04) was refused with 400, code 12130
# `access.api.error.missing_client_id_or_client_secret`. ZITADEL ignores it:
# the application authenticates with OIDC_AUTH_METHOD_TYPE_NONE, and on a
# local v4.19.2 a token request for such a client succeeded with this kind of
# placeholder sent by client_secret_basic, by client_secret_post, and empty,
# while one without a valid code_verifier was refused
# (https://github.com/mctlhq/mctl-gitops/issues/1500#issuecomment-5978313040).
# What protects the code is PKCE and the pinned redirect URI, not this value,
# so it can sit in a public repository.
#
# Cloudflare never returns it on read. Provider 5.24.0 keeps the state value
# when the API answers null (normalizeReadZeroTrustIDPConfigData), so a
# refresh does not plan a diff; the provider's acceptance tests set
# client_secret and assert an empty follow-up plan (resource_test.go). No
# ignore_changes is needed.

# Generated by ZITADEL, read from zitadel/cloudflare-access-oidc (key
# clientID; docs/runbooks/zitadel.md). Not a secret: it is sent in the clear
# in every authorization request. A recreate of the ZITADEL application
# changes it; zitadel-iac refuses that with prevent_destroy.
variable "zitadel_access_client_id" {
  description = "client_id of zitadel_application_oidc.cloudflare_access (public PKCE client)."
  type        = string
  # Read from zitadel/cloudflare-access-oidc after #1575 applied (2026-10-04).
  default = "393612693447116501"

  validation {
    condition     = can(regex("^[0-9]+$", var.zitadel_access_client_id))
    error_message = "zitadel_access_client_id must be the numeric ZITADEL client id."
  }
}

resource "cloudflare_zero_trust_access_identity_provider" "zitadel" {
  account_id = var.account_id
  # The label on the Access login picker; ZITADEL at auth.mctl.ai is the
  # provider. Renaming is an in-place update (only account_id, zone_id and
  # type force a replace), so the id other resources reference stays.
  name = "MCTL"
  type = "oidc"

  config = {
    client_id = var.zitadel_access_client_id
    # Placeholder required by the API; see the header. Not a secret.
    client_secret = "public-client-pkce"
    # Endpoints from https://auth.mctl.ai/.well-known/openid-configuration.
    auth_url  = "https://auth.mctl.ai/oauth/v2/authorize"
    token_url = "https://auth.mctl.ai/oauth/v2/token"
    certs_url = "https://auth.mctl.ai/oauth/v2/keys"
    # ZITADEL advertises S256 only, and refuses a token request for this
    # client without a code_verifier.
    pkce_enabled     = true
    scopes           = ["openid", "email", "profile"]
    email_claim_name = "email"
  }
}

# Throwaway application for the owner's one test login, and the target of
# #1329's login probe. Remove it once a real application offers ZITADEL.
#
# No DNS record: `A *.mctl.ai` is proxied (zones/mctl-ai/dns.tf), so Access
# sits in front of this host. Behind it the cluster ingress has no route
# for the name, so a successful login ends on a 404 from the origin; the
# identity Access derived is at /cdn-cgi/access/get-identity.
resource "cloudflare_zero_trust_access_application" "zitadel_test" {
  account_id = var.account_id
  name       = "ZITADEL sign-in test (access-zitadel-test.mctl.ai)"
  type       = "self_hosted"
  domain     = "access-zitadel-test.mctl.ai"

  destinations = [
    {
      type = "public"
      uri  = "access-zitadel-test.mctl.ai"
    },
  ]

  # ZITADEL alone, so the test cannot pass through another provider.
  allowed_idps              = [cloudflare_zero_trust_access_identity_provider.zitadel.id]
  auto_redirect_to_identity = true
  app_launcher_visible      = false
  session_duration          = "1h"

  # Anyone ZITADEL lets through. ZITADEL is the gate here: the `Cloudflare
  # Access` project refuses every user without its `access` role
  # (project_role_check), and that role is held by exactly the Argo CD
  # admins (zitadel-iac iac/cloudflare-access.tf). Matching an e-mail as well
  # would repeat that list in this public repository, and with the address
  # of a user whose ZITADEL profile can change outside Git.
  policies = [
    {
      name       = "zitadel-test-any-zitadel-login"
      decision   = "allow"
      precedence = 1

      include = [
        { login_method = { id = cloudflare_zero_trust_access_identity_provider.zitadel.id } },
      ]
    },
  ]
}

output "zitadel_idp_id" {
  description = "Access identity provider id of ZITADEL, for allowed_idps elsewhere."
  value       = cloudflare_zero_trust_access_identity_provider.zitadel.id
}
