apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-credentials
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: argocd-repo-mctl-app
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        url: https://github.com/mctlhq/mctl-gitops.git
        username: argocd
        password: '{{ `{{ .password }}` }}'
  data:
    - secretKey: password
      remoteRef:
        key: platform/argocd/github-repo
        property: pat
