apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-ghcr
  namespace: backstage
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: ghcr-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ `{{ .dockerconfigjson }}` }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: preview/backstage/ghcr-credentials
        property: dockerconfigjson
