apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Services and workers

  sourceRepos:
    - {{ .Values.spec.source.repoURL }}

  destinations:
    - server: {{ .Values.spec.destination.server }}
      namespace: "*"

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: ""
      kind: "*"
    - group: apps
      kind: "*"
    - group: networking.k8s.io
      kind: "*"
    - group: autoscaling
      kind: "*"
    - group: batch
      kind: "*"
    - group: external-secrets.io
      kind: "*"

  orphanedResources:
    warn: true
