apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kuptsi-v2
  description: "kuptsi-v2 service deployed to preview"
  annotations:
    backstage.io/kubernetes-id: kuptsi-v2
    argocd/app-name: preview-internal-kuptsi-v2
  labels:
    team: internal
    env: preview
spec:
  type: service
  lifecycle: production
  owner: group:internal
  system: team-internal
