apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-e2e-test
  description: "backstage-e2e-test service deployed to preview"
  annotations:
    backstage.io/kubernetes-id: backstage-e2e-test
    argocd/app-name: preview-bots-backstage-e2e-test
  labels:
    team: bots
    env: preview
spec:
  type: service
  lifecycle: production
  owner: group:bots
