# Service: mctl-web
# Team: admin
# Environment: preview
# Chart: base-service

image:
  repository: ghcr.io/mctlhq/mctl-web
  tag: "1.0.55"
imagePullSecrets:
  - name: ghcr-credentials
service:
  port: 80
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  APP_ENV: preview
ingress:
  enabled: true
  host: mctl.me
  hosts:
    - mctl.me
    - mctl.ru
  tls:
    - secretName: mctl-web-tls
      hosts:
        - mctl.me
        - mctl.ru
probes:
  liveness: null
  readiness: null
