# Service: mctl-web
# Team: admins
# Environment: production
# Chart: base-service

image:
  repository: ghcr.io/mctlhq/mctl-web
  tag: "4.4.4"
imagePullSecrets:
  - name: ghcr-credentials
service:
  port: 80
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env: {}
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - mctl.me
    - mctl.ru
    - mctl.ai
  tls:
    - secretName: mctl-web-tls
      hosts:
        - mctl.me
        - mctl.ru
        - mctl.ai
probes:
  liveness: null
  readiness: null
blueGreen:
  enabled: true
  autoPromotionEnabled: true
externalSecret: {}
envFrom: []
