# Worker: monteexchange
# Team: mashkovd
# Environment: preview
# Chart: worker-service

image:
  repository: ghcr.io/dmitriimashkov/monteexchange
  tag: "latest"

imagePullSecrets:
  - name: ghcr-credentials

workloadType: deployment

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  APP_ENV: preview

externalSecret:
  targetSecret: monteexchange-secrets
  data:
    - secretKey: BALANCE_ID
      remoteKey: teams/mashkovd/monteexchange
      property: BALANCE_ID
    - secretKey: BOT_TOKEN
      remoteKey: teams/mashkovd/monteexchange
      property: BOT_TOKEN
    - secretKey: PROFILE_ID
      remoteKey: teams/mashkovd/monteexchange
      property: PROFILE_ID
    - secretKey: WISE_HOST
      remoteKey: teams/mashkovd/monteexchange
      property: WISE_HOST
    - secretKey: WISE_TOKEN
      remoteKey: teams/mashkovd/monteexchange
      property: WISE_TOKEN

envFrom:
  - secretRef:
      name: monteexchange-secrets
