# Service: mctl-design
# Team: admins

# Chart: base-service

image:
  repository: ghcr.io/mctlhq/mctl-design
  tag: "1df4a279a3b9ef28eebcc83db2bfe8f9fee3de4b"
imagePullSecrets:
  - name: ghcr-credentials
service:
  port: 80
backstage:
  kubernetesId: mctl-design
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  APP_ENV: production
ingress:
  enabled: true
  hosts:
    - ui.mctl.ai
    - admins-mctl-design.mctl.ai
    - admins-mctl-design.mctl.me
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: mctl-design-tls
      hosts:
        - ui.mctl.ai
        - admins-mctl-design.mctl.ai
        - admins-mctl-design.mctl.me
extraContainers: []
