apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tenant-eee
  namespace: default
  description: "Tenant eee — namespace, quotas, and network policies"
  annotations:
    mctl.me/tenant-name: "eee"
    backstage.io/managed-by-location: "url:https://github.com/mctlhq/mctl-gitops/blob/main/platform-gitops/tenants/eee/catalog-info.yaml"
    backstage.io/managed-by-origin-location: "url:https://github.com/mctlhq/mctl-gitops/blob/main/platform-gitops/tenants/eee/catalog-info.yaml"
spec:
  type: tenant
  owner: group:default/admins
  system: team-eee
  dependsOn: []
