# Service: quirestack-api
# Team: nfc

# Chart: base-service

image:
  repository: ghcr.io/mctlhq/quirestack-api
  tag: "0.1.5"
imagePullSecrets:
  - name: ghcr-credentials
service:
  port: 3001
backstage:
  kubernetesId: quirestack-api
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  APP_ENV: production
  IMPORT_TOKEN: 3d86adebf681b43cb3258ac2ca8e379f3b49ddcfacb397b2
ingress:
  enabled: true
  hosts:
    - nfc-quirestack-api.mctl.ai
    - nfc-quirestack-api.mctl.me
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    - secretName: quirestack-api-tls
      hosts:
        - nfc-quirestack-api.mctl.ai
        - nfc-quirestack-api.mctl.me
envFrom:
  - secretRef:
      name: nfc-quirestack-api-db-creds
dbSecret:
  vaultPath: teams/nfc/quirestack-api/database
  secretName: nfc-quirestack-api-db-creds
externalSecret:
  targetSecret: quirestack-api-secrets
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteKey: teams/nfc/quirestack-api
      property: BETTER_AUTH_SECRET
