# DNS for mctl.ai — the zone that actually serves the platform.
#
# Generated by `tofu plan -generate-config-out`, then reduced (the generator
# emits every optional attribute as an explicit null) and re-planned. Do not
# hand-write these bodies: on mctl.me the same reduction silently changed two
# TTLs, and only the re-plan caught it.
#
# `A *.mctl.ai` is the path for every tenant host. Treat it as load-bearing.

locals {
  origin_ip = "91.98.10.188"
}

resource "cloudflare_dns_record" "mx_route2" {
  content  = "route2.mx.cloudflare.net"
  name     = "mctl.ai"
  priority = 28
  proxied  = false
  ttl      = 1
  type     = "MX"
  zone_id  = local.zone_id
}

resource "cloudflare_dns_record" "send_spf" {
  content = "\"v=spf1 include:amazonses.com ~all\""
  name    = "send.mctl.ai"
  proxied = false
  ttl     = 3600
  type    = "TXT"
  zone_id = local.zone_id
}

resource "cloudflare_dns_record" "mx_route1" {
  content  = "route1.mx.cloudflare.net"
  name     = "mctl.ai"
  priority = 99
  proxied  = false
  ttl      = 1
  type     = "MX"
  zone_id  = local.zone_id
}

resource "cloudflare_dns_record" "dmarc" {
  content = "\"v=DMARC1; p=none; rua=mailto:support@mctl.ai\""
  name    = "_dmarc.mctl.ai"
  proxied = false
  ttl     = 1
  type    = "TXT"
  zone_id = local.zone_id
}

resource "cloudflare_dns_record" "mx_route3" {
  content  = "route3.mx.cloudflare.net"
  name     = "mctl.ai"
  priority = 15
  proxied  = false
  ttl      = 1
  type     = "MX"
  zone_id  = local.zone_id
}

resource "cloudflare_dns_record" "spf" {
  content = "\"v=spf1 include:_spf.google.com include:_spf.mx.cloudflare.net include:amazonses.com ~all\""
  name    = "mctl.ai"
  proxied = false
  ttl     = 1
  type    = "TXT"
  zone_id = local.zone_id
}

resource "cloudflare_dns_record" "gh_org_verify" {
  content = "\"90e6081e86\""
  name    = "_gh-mctlhq-o.mctl.ai"
  proxied = false
  ttl     = 1
  type    = "TXT"
  zone_id = local.zone_id
}

resource "cloudflare_dns_record" "wildcard" {
  content = "91.98.10.188"
  name    = "*.mctl.ai"
  proxied = true
  ttl     = 1
  type    = "A"
  zone_id = local.zone_id
}

resource "cloudflare_dns_record" "apex" {
  content = "91.98.10.188"
  name    = "mctl.ai"
  proxied = true
  ttl     = 1
  type    = "A"
  zone_id = local.zone_id
}

resource "cloudflare_dns_record" "cf_dkim" {
  content = "\"v=DKIM1; h=sha256; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiweykoi+o48IOGuP7GR3X0MOExCUDY/BCRHoWBnh3rChl7WhdyCxW3jgq1daEjPPqoi7sJvdg5hEQVsgVRQP4DcnQDVjGMbASQtrY4WmB1VebF+RPJB2ECPsEDTpeiI5ZyUAwJaVX7r6bznU67g7LvFq35yIo4sdlmtZGV+i0H4cpYH9+3JJ78k\" \"m4KXwaf9xUJCWF6nxeD+qG6Fyruw1Qlbds2r85U9dkNDVAS3gioCvELryh1TxKGiVTkg4wqHTyHfWsp7KD3WQHYJn0RyfJJu6YEmL77zonn7p2SRMvTMP3ZEXibnC9gz3nnhR6wcYL8Q7zXypKTMD58bTixDSJwIDAQAB\""
  name    = "cf2024-1._domainkey.mctl.ai"
  proxied = false
  ttl     = 1
  type    = "TXT"
  zone_id = local.zone_id
}

resource "cloudflare_dns_record" "resend_dkim" {
  content = "\"p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCpbLniQh1oJtei2zCcrvyiVG5kBcV1WE0otGuQ9Gm1QIVsUHWCOxZulCV727JIJDRAbOrzh+3wjHYmb3NUoF9tZt1qYMNGIApxayAqjIpX3SGVL8e3E46JCw3gEM6Sci536qeptzQwzfd4r5vtDoIEziEic4X7ivq9KbO7QcsrzwIDAQAB\""
  name    = "resend._domainkey.mctl.ai"
  proxied = false
  ttl     = 3600
  type    = "TXT"
  zone_id = local.zone_id
}

resource "cloudflare_dns_record" "send_mx" {
  content  = "feedback-smtp.eu-west-1.amazonses.com"
  name     = "send.mctl.ai"
  priority = 10
  proxied  = false
  ttl      = 3600
  type     = "MX"
  zone_id  = local.zone_id
}
