#!/usr/bin/env python3
"""Materialize enabled platform-catalog skills into per-tenant OpenClaw values.

For every tenant this renders
  platform-gitops/services/<tenant>/openclaw/generated/platform-skills-values.yaml
from the platform-skills catalog and the tenant's binding file. The file is a
second Helm valueFile of the {tenant}-openclaw-skills Application (see
bootstrap/templates/bootstrap/applicationset-openclaw-skills.yaml); its
`skills:` map merges with the tenant-authored skills-values.yaml, tenant file
winning per-key collisions.

A skill materializes for a tenant only when ALL hold:
  - listed in bindings/tenants/<tenant>.yaml enabledSkills
  - exists in catalog/ with visibility "tenant" and status active|deprecated
    (deprecated stays materialized until explicitly disabled)
  - "openclaw" is in its runtimes list
  - allowed by policy.yaml (not denylisted; inside the allowlist when one is
    set for the tenant — mirror of the mctl-api enable preflight)
Tenants without a services/<tenant>/openclaw/ dir are skipped. An empty
effective set removes the generated file (the Application uses
ignoreMissingValueFiles).

Known v1 limitation: catalog references/*.md are NOT shipped — the fanout
sidecar only maps <name>.md ConfigMap keys to skills/<name>/SKILL.md.

Run by the platform-skill-{publish,deprecate,enable,disable} workflows; CI
runs `--check` to catch hand edits leaving generated files stale.
"""
import argparse
import io
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parents[1]
BASE = ROOT / "platform-gitops"
CATALOG = BASE / "platform-skills" / "catalog"
BINDINGS = BASE / "platform-skills" / "bindings" / "tenants"
POLICY = BASE / "platform-skills" / "policy.yaml"
SERVICES = BASE / "services"

HEADER = (
    "# Auto-generated by scripts/materialize-openclaw-platform-skills.py\n"
    "# (run by the platform-skill-* workflows).\n"
    "# Do not edit manually — changes will be overwritten on the next platform-skill change.\n"
)

WARN_BYTES = 512 * 1024
FAIL_BYTES = 900 * 1024


def load_yaml(path):
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def load_catalog():
    catalog = {}
    for skill_dir in sorted(CATALOG.glob("*")) if CATALOG.exists() else []:
        meta_path = skill_dir / "metadata.yaml"
        if not skill_dir.is_dir() or not meta_path.exists():
            continue
        catalog[skill_dir.name] = load_yaml(meta_path)
    return catalog


def all_tenants():
    tenants = set()
    for path in sorted(BINDINGS.glob("*.yaml")) if BINDINGS.exists() else []:
        tenants.add(load_yaml(path).get("tenant") or path.stem)
    for openclaw_dir in sorted(SERVICES.glob("*/openclaw")) if SERVICES.exists() else []:
        tenants.add(openclaw_dir.parent.name)
    return sorted(tenants)


def effective_skills(tenant, catalog, policy, errors):
    def skip(skill, reason):
        print(f"skip {tenant}/{skill}: {reason}")

    binding_path = BINDINGS / f"{tenant}.yaml"
    binding = load_yaml(binding_path)
    declared = binding.get("tenant")
    if declared and declared != tenant:
        errors.append(f"{binding_path}: tenant field {declared!r} does not match filename")
        return None
    enabled = binding.get("enabledSkills") or []
    denylist = (policy.get("tenantDenylist") or {}).get(tenant) or []
    # Allowlist absent (no key for the tenant) = unrestricted; an explicit
    # empty list = deny-all, so admins can block all platform skills for a
    # tenant without touching every binding. Stricter than mctl-api's enable
    # preflight, which currently treats an empty list as unrestricted
    # (validateTenantSkillEnable: `ok && len(allowed) > 0`) — align the API
    # side before relying on empty-list semantics there.
    allowlist = (policy.get("tenantAllowlist") or {}).get(tenant)
    skills = {}
    for name in sorted(set(enabled)):
        meta = catalog.get(name)
        if meta is None:
            skip(name, "not in catalog")
        elif meta.get("visibility") != "tenant":
            skip(name, f"visibility {meta.get('visibility')!r} is not tenant")
        elif meta.get("status") not in {"active", "deprecated"}:
            skip(name, f"status {meta.get('status')!r} is not active/deprecated")
        elif "openclaw" not in (meta.get("runtimes") or []):
            skip(name, "openclaw not in runtimes")
        elif name in denylist:
            skip(name, "denylisted in policy.yaml")
        elif allowlist is not None and name not in allowlist:
            skip(name, "not in policy.yaml allowlist for this tenant")
        elif not (CATALOG / name / "SKILL.md").is_file():
            # Incomplete catalog entry (validate-platform-skills.py flags it
            # too) — degrade to a skip so --check reports cleanly in CI.
            skip(name, "catalog entry has no SKILL.md")
        else:
            skills[name] = (CATALOG / name / "SKILL.md").read_text(encoding="utf-8")
    return skills


def render(skills):
    buf = io.StringIO()
    buf.write(HEADER)
    yaml.safe_dump(
        {"skills": skills},
        buf,
        allow_unicode=True,
        default_style="|",
        sort_keys=False,
        width=4096,
    )
    return buf.getvalue()


def size_and_collision_guard(tenant, expected, errors):
    tenant_values_path = SERVICES / tenant / "openclaw" / "generated" / "skills-values.yaml"
    tenant_values = load_yaml(tenant_values_path)
    # Only the skills: map lands in the {team}-openclaw-skills ConfigMap;
    # identity: goes to a separate ConfigMap and must not count here.
    tenant_skills = tenant_values.get("skills") or {}
    tenant_skills_bytes = sum(
        len(str(key).encode("utf-8")) + len(str(value).encode("utf-8"))
        for key, value in tenant_skills.items()
    )
    total = len(expected.encode("utf-8")) + tenant_skills_bytes
    if total > FAIL_BYTES:
        errors.append(
            f"{tenant}: combined skills values {total} bytes exceed {FAIL_BYTES}"
            " (single ConfigMap, ~1MiB etcd cap)"
        )
    elif total > WARN_BYTES:
        print(f"warn {tenant}: combined skills values {total} bytes (> {WARN_BYTES})")
    platform_keys = set((yaml.safe_load(expected) or {}).get("skills") or {})
    for name in sorted(platform_keys & set(tenant_skills)):
        print(
            f"warn {tenant}: skill {name!r} exists both in catalog binding and"
            " tenant skills — tenant-authored version wins the Helm merge"
        )


def materialize(tenant, catalog, policy, check, errors):
    target = SERVICES / tenant / "openclaw" / "generated" / "platform-skills-values.yaml"
    skills = {}
    if (SERVICES / tenant / "openclaw").is_dir():
        skills = effective_skills(tenant, catalog, policy, errors)
        if skills is None:
            # Broken binding — leave the tenant's current state untouched.
            return
    if not skills:
        if target.exists():
            if check:
                errors.append(f"drift {tenant}: {target} should not exist")
            else:
                target.unlink()
                print(f"removed {tenant} (0 skills)")
        else:
            print(f"ok {tenant} (0 skills)")
        return
    expected = render(skills)
    size_and_collision_guard(tenant, expected, errors)
    current = target.read_text(encoding="utf-8") if target.exists() else None
    if current == expected:
        print(f"ok {tenant} ({len(skills)} skills)")
    elif check:
        errors.append(f"drift {tenant}: {target} is stale — rerun this script")
    else:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(expected, encoding="utf-8")
        print(f"wrote {tenant} ({len(skills)} skills)")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    scope = parser.add_mutually_exclusive_group()
    scope.add_argument("--tenant", help="materialize a single tenant")
    scope.add_argument("--all", action="store_true", help="materialize every tenant")
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated files are up to date; exit 1 on drift",
    )
    args = parser.parse_args()
    if not args.tenant and not args.all and not args.check:
        parser.error("one of --tenant, --all or --check is required")

    catalog = load_catalog()
    policy = load_yaml(POLICY)
    tenants = [args.tenant] if args.tenant else all_tenants()
    errors = []
    for tenant in tenants:
        materialize(tenant, catalog, policy, args.check, errors)
    for error in errors:
        print(error, file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
