#!/usr/bin/env python3
"""Materialize the DevLoop trace fixtures into the Argo Workflows ConfigMap.

issue-903 (mctl-gitops half): the `otel-trace-fixture` emitter
(`platform-gitops/argo-workflows/cluster-templates/wft-otel-trace-fixture.yaml`)
needs the fixture bytes available inside its pod, but `tests/fixtures/*.json`
is the single source of truth reviewed by every fixture test
(`tests/test_devloop_trace_fixture.py`). Rather than maintain two divergent
copies, this script renders
`platform-gitops/argo-workflows/config/otel-trace-fixture-configmap.yaml`
from `tests/fixtures/devloop-trace.json` and
`tests/fixtures/devloop-trace-redaction.json`, the same generate-then-`--check`
contract `scripts/materialize-openclaw-platform-skills.py` already has in
`.github/workflows/validate-manifests.yml`.

The ConfigMap lands in `argo-workflows` because that is the namespace
`platform-gitops/bootstrap/templates/core-infra/argo-workflows-config.yaml`
syncs `platform-gitops/argo-workflows` into, and the namespace the emitter
pod itself runs in.

Run with --selftest to prove the drift detector actually detects drift: a
checker that has never been seen to fire is not known to work.

Run: python3 scripts/materialize-otel-trace-fixture.py [--check] [--selftest]
"""
import argparse
import json
import pathlib
import shutil
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "tests" / "fixtures"
TARGET = ROOT / "platform-gitops" / "argo-workflows" / "config" / "otel-trace-fixture-configmap.yaml"

SOURCES = {
    "devloop-trace.json": FIXTURES / "devloop-trace.json",
    "devloop-trace-redaction.json": FIXTURES / "devloop-trace-redaction.json",
}

HEADER = (
    "# Auto-generated by scripts/materialize-otel-trace-fixture.py.\n"
    "# Source of truth: tests/fixtures/devloop-trace.json and\n"
    "# tests/fixtures/devloop-trace-redaction.json.\n"
    "# Do not edit manually -- CI runs --check and fails on drift.\n"
)


def render(sources):
    lines = [HEADER]
    lines.append("apiVersion: v1")
    lines.append("kind: ConfigMap")
    lines.append("metadata:")
    lines.append("  name: otel-trace-fixture")
    lines.append("  namespace: argo-workflows")
    lines.append("data:")
    for key in sorted(sources):
        path = sources[key]
        # Validate as JSON before embedding -- a materializer that faithfully
        # copies broken JSON into a ConfigMap is worse than one that refuses.
        json.loads(path.read_text(encoding="utf-8"))
        lines.append(f"  {key}: |")
        for line in path.read_text(encoding="utf-8").splitlines():
            lines.append(f"    {line}" if line else "")
    return "\n".join(lines) + "\n"


def check(sources, target):
    expected = render(sources)
    if not target.exists():
        return False, f"{target} does not exist -- run this script with no arguments"
    current = target.read_text(encoding="utf-8")
    if current != expected:
        return False, f"{target} is stale -- rerun scripts/materialize-otel-trace-fixture.py"
    return True, ""


def selftest():
    """Build a throwaway tree; --check must pass fresh and fail after a byte edit."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        fixtures_dir = tmp / "fixtures"
        fixtures_dir.mkdir()
        config_dir = tmp / "config"
        config_dir.mkdir()
        sample = {"resourceSpans": [{"resource": {"attributes": []}, "scopeSpans": []}]}
        sample_path = fixtures_dir / "devloop-trace.json"
        sample_path.write_text(json.dumps(sample, indent=2) + "\n")
        redaction_path = fixtures_dir / "devloop-trace-redaction.json"
        redaction_path.write_text(json.dumps(sample, indent=2) + "\n")
        srcs = {
            "devloop-trace.json": sample_path,
            "devloop-trace-redaction.json": redaction_path,
        }
        target = config_dir / "otel-trace-fixture-configmap.yaml"

        ok, msg = check(srcs, target)
        assert not ok, "check() passed on a target that does not exist yet"

        target.write_text(render(srcs))
        ok, msg = check(srcs, target)
        assert ok, f"check() failed on a freshly generated ConfigMap: {msg}"

        # Perturb one fixture by a single byte and prove drift is caught.
        perturbed = json.loads(sample_path.read_text())
        perturbed["resourceSpans"][0]["resource"]["attributes"].append(
            {"key": "x", "value": {"stringValue": "y"}})
        sample_path.write_text(json.dumps(perturbed, indent=2) + "\n")
        ok, msg = check(srcs, target)
        assert not ok, "check() did not detect a one-fixture-byte drift"
    print("selftest: materializer detects a fresh generation and a drifted one")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the ConfigMap is up to date; exit 1 on drift")
    parser.add_argument("--selftest", action="store_true", help="prove the detector fires, using a throwaway tree")
    args = parser.parse_args()

    if args.selftest:
        selftest()
        return 0

    if args.check:
        ok, msg = check(SOURCES, TARGET)
        if not ok:
            print(f"FAIL: {msg}", file=sys.stderr)
            return 1
        print("ok: otel-trace-fixture ConfigMap is up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(render(SOURCES))
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
