#!/usr/bin/env python3
"""Machine-check the SOC F4 "tenant roles get no exec" control.

Tenant Argo CD RBAC now lives one file per tenant under
`platform-gitops/argocd/rbac/tenants/<tenant>.csv`
(mctlhq/mctl-gitops#1431) instead of as blocks inside the shared
`platform-gitops/argocd/values.yaml`. That move only keeps its safety
property if three things stay true:

1. Every tenant directory under `platform-gitops/tenants/` has exactly one
   matching fragment, and vice versa — `admins` is the one exemption, since
   its access comes from the base policy's `g, admins, role:admin` line, not
   a `role:team-admins` block; a fragment for it would change effective
   policy and is itself a failure, not a silent pass.
2. Every fragment is byte-equal to the canonical six-line rendering for its
   tenant name — no extra verb, no widened object glob, and critically no
   `exec` grant can be slipped into a fragment by hand.
3. `platform-gitops/argocd/values.yaml` has no `role:team-` line left in it —
   a hand-edit reintroducing the pre-migration pattern must fail this.

Run with --selftest to prove the detector still detects.
"""

from __future__ import annotations

import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TENANTS_DIR = ROOT / "platform-gitops/tenants"
FRAGMENTS_DIR = ROOT / "platform-gitops/argocd/rbac/tenants"
VALUES_FILE = ROOT / "platform-gitops/argocd/values.yaml"

# admins' access comes from the base policy's "g, admins, role:admin" line,
# not a role:team-admins block. A rbac/tenants/admins.csv would change
# effective policy and must be flagged, not silently allowed.
EXEMPT_TENANTS = {"admins"}


def canonical_fragment(tenant: str) -> str:
    return (
        f"# Tenant: {tenant} — generated by wft-create-tenant. No exec (SOC F4).\n"
        f"p, role:team-{tenant}, applications, get, apps/{tenant}-*, allow\n"
        f"p, role:team-{tenant}, applications, list, apps/{tenant}-*, allow\n"
        f"p, role:team-{tenant}, applications, sync, apps/{tenant}-*, allow\n"
        f"p, role:team-{tenant}, applications, override, apps/{tenant}-*, allow\n"
        f"p, role:team-{tenant}, logs, get, apps/{tenant}-*, allow\n"
        f"g, {tenant}, role:team-{tenant}\n"
    )


def tenant_dirs(tenants_dir: Path) -> set[str]:
    if not tenants_dir.is_dir():
        return set()
    return {p.name for p in tenants_dir.iterdir() if p.is_dir()}


def fragment_tenants(fragments_dir: Path) -> set[str]:
    if not fragments_dir.is_dir():
        return set()
    return {p.stem for p in fragments_dir.glob("*.csv")}


def check(tenants_dir: Path, fragments_dir: Path, values_file: Path) -> list[str]:
    problems: list[str] = []

    dirs = tenant_dirs(tenants_dir)
    fragments = fragment_tenants(fragments_dir)

    expected_fragments = dirs - EXEMPT_TENANTS

    for tenant in sorted(expected_fragments - fragments):
        problems.append(
            f"tenant directory platform-gitops/tenants/{tenant}/ has no "
            f"matching rbac/tenants/{tenant}.csv fragment"
        )
    for tenant in sorted(fragments - dirs):
        problems.append(
            f"rbac/tenants/{tenant}.csv has no matching tenant directory "
            f"platform-gitops/tenants/{tenant}/"
        )
    for tenant in sorted(fragments & EXEMPT_TENANTS):
        problems.append(
            f"rbac/tenants/{tenant}.csv exists for exempt tenant '{tenant}' — "
            f"its access comes from the base policy's 'g, admins, role:admin' "
            f"line; a fragment here changes effective policy"
        )

    for tenant in sorted(fragments):
        if tenant in EXEMPT_TENANTS:
            continue
        frag_path = fragments_dir / f"{tenant}.csv"
        content = frag_path.read_text()
        expected = canonical_fragment(tenant)
        if content != expected:
            problems.append(
                f"rbac/tenants/{tenant}.csv is not byte-equal to the canonical "
                f"six-line rendering for '{tenant}' (extra/removed verb, widened "
                f"glob, added exec, or other hand-edit)"
            )

    if values_file.is_file():
        text = values_file.read_text()
        for lineno, line in enumerate(text.splitlines(), start=1):
            if "role:team-" in line:
                problems.append(
                    f"{values_file.relative_to(ROOT)}:{lineno} still contains "
                    f"'role:team-' — tenant RBAC must live only in "
                    f"rbac/tenants/*.csv"
                )

    return problems


def _write_tree(base: Path, tenants: dict[str, bool], fragments: dict[str, str]):
    """tenants: name -> True (create dir). fragments: name -> content."""
    tenants_dir = base / "tenants"
    fragments_dir = base / "argocd" / "rbac" / "tenants"
    tenants_dir.mkdir(parents=True, exist_ok=True)
    fragments_dir.mkdir(parents=True, exist_ok=True)
    for name in tenants:
        (tenants_dir / name).mkdir(parents=True, exist_ok=True)
    for name, content in fragments.items():
        (fragments_dir / f"{name}.csv").write_text(content)
    values_file = base / "argocd" / "values.yaml"
    values_file.parent.mkdir(parents=True, exist_ok=True)
    values_file.write_text("configs:\n  rbac:\n    policy.csv: |\n      g, admins, role:admin\n")
    return tenants_dir, fragments_dir, values_file


def selftest() -> int:
    """Each scratch case runs in its own temp dir; nothing touches the real tree."""

    # (a) exec line slipped into a fragment.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        content = canonical_fragment("labs") + "p, role:team-labs, exec, create, apps/labs-*, allow\n"
        t, f, v = _write_tree(base, {"labs": True}, {"labs": content})
        if not check(t, f, v):
            print("FAIL selftest(a): exec line in fragment was not caught", file=sys.stderr)
            return 1

    # (b) widened object glob.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        content = canonical_fragment("labs").replace("apps/labs-*", "apps/*")
        t, f, v = _write_tree(base, {"labs": True}, {"labs": content})
        if not check(t, f, v):
            print("FAIL selftest(b): widened glob was not caught", file=sys.stderr)
            return 1

    # (c) tenant directory with no fragment.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        t, f, v = _write_tree(base, {"labs": True}, {})
        if not check(t, f, v):
            print("FAIL selftest(c): missing fragment for a tenant dir was not caught", file=sys.stderr)
            return 1

    # (d) fragment with no tenant directory.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        t, f, v = _write_tree(base, {}, {"labs": canonical_fragment("labs")})
        if not check(t, f, v):
            print("FAIL selftest(d): orphan fragment was not caught", file=sys.stderr)
            return 1

    # (e) admins.csv fragment present.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        t, f, v = _write_tree(base, {"admins": True}, {"admins": canonical_fragment("admins")})
        if not check(t, f, v):
            print("FAIL selftest(e): admins.csv fragment was not caught", file=sys.stderr)
            return 1

    # Silent on a reconstruction of the real post-migration tree: labs/ovk/karabu
    # fragments + admins/labs/karabu/ovk tenant dirs, admins exempt.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        tenants = {"admins": True, "labs": True, "ovk": True, "karabu": True}
        fragments = {
            "labs": canonical_fragment("labs"),
            "ovk": canonical_fragment("ovk"),
            "karabu": canonical_fragment("karabu"),
        }
        t, f, v = _write_tree(base, tenants, fragments)
        problems = check(t, f, v)
        if problems:
            print(f"FAIL selftest: false positive on the real post-migration tree: {problems}", file=sys.stderr)
            return 1

    print(
        "OK selftest: detector fires on an added exec line, a widened glob, a "
        "missing fragment, an orphan fragment, and an admins.csv fragment, and "
        "stays silent on the real post-migration tree"
    )
    return 0


def main() -> int:
    if "--selftest" in sys.argv:
        return selftest()

    if not TENANTS_DIR.is_dir():
        print(f"::error::{TENANTS_DIR} not found — refusing to pass vacuously", file=sys.stderr)
        return 2
    if not FRAGMENTS_DIR.is_dir():
        print(f"::error::{FRAGMENTS_DIR} not found — refusing to pass vacuously", file=sys.stderr)
        return 2

    problems = check(TENANTS_DIR, FRAGMENTS_DIR, VALUES_FILE)
    if problems:
        for p in problems:
            print(f"::error::{p}", file=sys.stderr)
        return 1

    print("OK: tenant directories and ArgoCD RBAC fragments are 1:1 and canonical")
    return 0


if __name__ == "__main__":
    sys.exit(main())
