#!/usr/bin/env python3
"""Machine-check the SOC F4 "tenant roles get no exec" control.

Tenant Argo CD RBAC now lives one file per tenant under
`platform-gitops/argocd/rbac/tenants/<tenant>.csv`
(mctlhq/mctl-gitops#1431) instead of as blocks inside the shared
`platform-gitops/argocd/values.yaml`. That move only keeps its safety
property if three things stay true:

1. Every tenant directory under `platform-gitops/tenants/` has exactly one
   matching fragment, and vice versa — `admins` is the one exemption, since
   its access comes from the base policy's `g, admins, role:admin` line, not
   a `role:team-admins` block; a fragment for it would change effective
   policy and is itself a failure, not a silent pass.
2. Every fragment is byte-equal to the canonical six-line rendering for its
   tenant name — no extra verb, no widened object glob, and critically no
   `exec` grant can be slipped into a fragment by hand. A tenant whose
   Applications live in an AppProject of its own (bootstrap/templates/
   projects/project-<tenant>.yaml, confined to namespace <tenant>) gets the
   same five verbs on `<tenant>/*` appended, and only then: the extension is
   derived from that file, never accepted on its own.
3. `platform-gitops/argocd/values.yaml` has no `role:team-` line left in it —
   a hand-edit reintroducing the pre-migration pattern must fail this.

Run with --selftest to prove the detector still detects.
"""

from __future__ import annotations

import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TENANTS_DIR = ROOT / "platform-gitops/tenants"
FRAGMENTS_DIR = ROOT / "platform-gitops/argocd/rbac/tenants"
VALUES_FILE = ROOT / "platform-gitops/argocd/values.yaml"
PROJECTS_DIR = ROOT / "platform-gitops/bootstrap/templates/projects"

# admins' access comes from the base policy's "g, admins, role:admin" line,
# not a role:team-admins block. A rbac/tenants/admins.csv would change
# effective policy and must be flagged, not silently allowed.
EXEMPT_TENANTS = {"admins"}


def _grants(tenant: str, obj: str) -> str:
    return (
        f"p, role:team-{tenant}, applications, get, {obj}, allow\n"
        f"p, role:team-{tenant}, applications, list, {obj}, allow\n"
        f"p, role:team-{tenant}, applications, sync, {obj}, allow\n"
        f"p, role:team-{tenant}, applications, override, {obj}, allow\n"
        f"p, role:team-{tenant}, logs, get, {obj}, allow\n"
    )


def canonical_fragment(tenant: str, has_own_project: bool = False) -> str:
    text = (
        f"# Tenant: {tenant} — generated by wft-create-tenant. No exec (SOC F4).\n"
        + _grants(tenant, f"apps/{tenant}-*")
        + f"g, {tenant}, role:team-{tenant}\n"
    )
    if has_own_project:
        text += (
            f"# AppProject {tenant} (bootstrap/templates/projects/project-{tenant}.yaml):"
            f" the same verbs on its Applications. No exec (SOC F4).\n"
            + _grants(tenant, f"{tenant}/*")
        )
    return text


def _block(lines: list[str], header: str, indent: int) -> list[str] | None:
    """The lines nested under the first line equal to `header` (trailing
    blanks ignored), up to the next line indented `indent` spaces or less.
    None when the header is absent."""
    for i, line in enumerate(lines):
        if line.rstrip() == header:
            body = []
            for nxt in lines[i + 1:]:
                if nxt.strip() and len(nxt) - len(nxt.lstrip(" ")) <= indent:
                    break
                body.append(nxt)
            return body
    return None


def own_project(tenant: str, projects_dir: Path) -> tuple[bool, str | None]:
    """Whether the tenant has an AppProject of its own that `<tenant>/*` may name.

    Returns (has_project, problem). The file is a Helm template, so it is read
    line by line rather than parsed: metadata.name must be the tenant, and
    every destination namespace must be the tenant's own. A project file that
    exists but fails either check is a problem, not "no project": granting
    `<tenant>/*` on a project that can reach other namespaces would widen the
    role beyond the tenant.
    """
    path = projects_dir / f"project-{tenant}.yaml"
    if not path.is_file():
        return False, None
    lines = path.read_text().splitlines()
    metadata = _block(lines, "metadata:", 0)
    names = [m.group(1) for l in metadata or [] for m in [re.match(r"  name:\s*(\S+)", l)] if m]
    if len(names) != 1 or names[0].strip("\"'") != tenant:
        return True, f"{path.name}: metadata.name is not '{tenant}'"
    destinations = _block(lines, "  destinations:", 2)
    if destinations is None:
        return True, f"{path.name}: no spec.destinations block found"
    namespaces = [m.group(1) for l in destinations for m in [re.search(r"namespace:\s*(\S+)", l)] if m]
    if not namespaces or any(ns.strip("\"'") != tenant for ns in namespaces):
        return True, (
            f"{path.name}: destinations must all be namespace '{tenant}', "
            f"got {namespaces or 'none'}"
        )
    return True, None


def tenant_dirs(tenants_dir: Path) -> set[str]:
    if not tenants_dir.is_dir():
        return set()
    return {p.name for p in tenants_dir.iterdir() if p.is_dir()}


def fragment_tenants(fragments_dir: Path) -> set[str]:
    if not fragments_dir.is_dir():
        return set()
    return {p.stem for p in fragments_dir.glob("*.csv")}


def check(
    tenants_dir: Path, fragments_dir: Path, values_file: Path, projects_dir: Path
) -> list[str]:
    problems: list[str] = []

    dirs = tenant_dirs(tenants_dir)
    fragments = fragment_tenants(fragments_dir)

    expected_fragments = dirs - EXEMPT_TENANTS

    for tenant in sorted(expected_fragments - fragments):
        problems.append(
            f"tenant directory platform-gitops/tenants/{tenant}/ has no "
            f"matching rbac/tenants/{tenant}.csv fragment"
        )
    for tenant in sorted(fragments - dirs):
        problems.append(
            f"rbac/tenants/{tenant}.csv has no matching tenant directory "
            f"platform-gitops/tenants/{tenant}/"
        )
    for tenant in sorted(fragments & EXEMPT_TENANTS):
        problems.append(
            f"rbac/tenants/{tenant}.csv exists for exempt tenant '{tenant}' — "
            f"its access comes from the base policy's 'g, admins, role:admin' "
            f"line; a fragment here changes effective policy"
        )

    for tenant in sorted(fragments):
        if tenant in EXEMPT_TENANTS:
            continue
        frag_path = fragments_dir / f"{tenant}.csv"
        content = frag_path.read_text()
        has_project, project_problem = own_project(tenant, projects_dir)
        if project_problem:
            problems.append(project_problem)
            continue
        expected = canonical_fragment(tenant, has_project)
        if content != expected:
            problems.append(
                f"rbac/tenants/{tenant}.csv is not byte-equal to the canonical "
                f"rendering for '{tenant}' (own AppProject: {has_project}; "
                f"extra/removed verb, widened glob, added exec, or other hand-edit)"
            )

    if values_file.is_file():
        text = values_file.read_text()
        for lineno, line in enumerate(text.splitlines(), start=1):
            if "role:team-" in line:
                problems.append(
                    f"{values_file.relative_to(ROOT)}:{lineno} still contains "
                    f"'role:team-' — tenant RBAC must live only in "
                    f"rbac/tenants/*.csv"
                )

    return problems


PROJECT_TEMPLATE = """apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {name}
  namespace: argocd
spec:
  destinations:
    - server: {{{{ .Values.spec.destination.server }}}}
      namespace: {namespace}

  clusterResourceWhitelist: []
"""


def _write_tree(
    base: Path,
    tenants: dict[str, bool],
    fragments: dict[str, str],
    projects: dict[str, str] | None = None,
):
    """tenants: name -> True (create dir). fragments: name -> content.
    projects: tenant -> AppProject file content."""
    tenants_dir = base / "tenants"
    fragments_dir = base / "argocd" / "rbac" / "tenants"
    tenants_dir.mkdir(parents=True, exist_ok=True)
    fragments_dir.mkdir(parents=True, exist_ok=True)
    for name in tenants:
        (tenants_dir / name).mkdir(parents=True, exist_ok=True)
    for name, content in fragments.items():
        (fragments_dir / f"{name}.csv").write_text(content)
    values_file = base / "argocd" / "values.yaml"
    values_file.parent.mkdir(parents=True, exist_ok=True)
    values_file.write_text("configs:\n  rbac:\n    policy.csv: |\n      g, admins, role:admin\n")
    projects_dir = base / "projects"
    projects_dir.mkdir(parents=True, exist_ok=True)
    for name, content in (projects or {}).items():
        (projects_dir / f"project-{name}.yaml").write_text(content)
    return tenants_dir, fragments_dir, values_file, projects_dir


def selftest() -> int:
    """Each scratch case runs in its own temp dir; nothing touches the real tree."""

    # (a) exec line slipped into a fragment.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        content = canonical_fragment("labs") + "p, role:team-labs, exec, create, apps/labs-*, allow\n"
        t, f, v, pr = _write_tree(base, {"labs": True}, {"labs": content})
        if not check(t, f, v, pr):
            print("FAIL selftest(a): exec line in fragment was not caught", file=sys.stderr)
            return 1

    # (b) widened object glob.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        content = canonical_fragment("labs").replace("apps/labs-*", "apps/*")
        t, f, v, pr = _write_tree(base, {"labs": True}, {"labs": content})
        if not check(t, f, v, pr):
            print("FAIL selftest(b): widened glob was not caught", file=sys.stderr)
            return 1

    # (c) tenant directory with no fragment.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        t, f, v, pr = _write_tree(base, {"labs": True}, {})
        if not check(t, f, v, pr):
            print("FAIL selftest(c): missing fragment for a tenant dir was not caught", file=sys.stderr)
            return 1

    # (d) fragment with no tenant directory.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        t, f, v, pr = _write_tree(base, {}, {"labs": canonical_fragment("labs")})
        if not check(t, f, v, pr):
            print("FAIL selftest(d): orphan fragment was not caught", file=sys.stderr)
            return 1

    # (e) admins.csv fragment present.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        t, f, v, pr = _write_tree(base, {"admins": True}, {"admins": canonical_fragment("admins")})
        if not check(t, f, v, pr):
            print("FAIL selftest(e): admins.csv fragment was not caught", file=sys.stderr)
            return 1

    own = PROJECT_TEMPLATE.format(name="erpact", namespace="erpact")

    # (f) own-project lines without an AppProject of that name.
    with tempfile.TemporaryDirectory() as d:
        t, f, v, pr = _write_tree(Path(d), {"erpact": True}, {"erpact": canonical_fragment("erpact", True)})
        if not check(t, f, v, pr):
            print("FAIL selftest(f): own-project grant without an AppProject was not caught", file=sys.stderr)
            return 1

    # (g) an AppProject of its own whose grant is missing from the fragment.
    with tempfile.TemporaryDirectory() as d:
        t, f, v, pr = _write_tree(
            Path(d), {"erpact": True}, {"erpact": canonical_fragment("erpact")}, {"erpact": own}
        )
        if not check(t, f, v, pr):
            print("FAIL selftest(g): missing own-project grant was not caught", file=sys.stderr)
            return 1

    # (h) the AppProject reaches another namespace: `<tenant>/*` would widen.
    with tempfile.TemporaryDirectory() as d:
        t, f, v, pr = _write_tree(
            Path(d),
            {"erpact": True},
            {"erpact": canonical_fragment("erpact", True)},
            {"erpact": PROJECT_TEMPLATE.format(name="erpact", namespace='"*"')},
        )
        if not check(t, f, v, pr):
            print("FAIL selftest(h): AppProject reaching other namespaces was not caught", file=sys.stderr)
            return 1

    # (i) the file is named after the tenant but declares another project.
    with tempfile.TemporaryDirectory() as d:
        t, f, v, pr = _write_tree(
            Path(d),
            {"erpact": True},
            {"erpact": canonical_fragment("erpact", True)},
            {"erpact": PROJECT_TEMPLATE.format(name="apps", namespace="erpact")},
        )
        if not check(t, f, v, pr):
            print("FAIL selftest(i): AppProject named differently from its tenant was not caught", file=sys.stderr)
            return 1

    # Silent on a reconstruction of the real tree: labs/ovk/karabu fragments,
    # erpact with its own AppProject, admins exempt.
    with tempfile.TemporaryDirectory() as d:
        base = Path(d)
        tenants = {"admins": True, "labs": True, "ovk": True, "karabu": True, "erpact": True}
        fragments = {
            "labs": canonical_fragment("labs"),
            "ovk": canonical_fragment("ovk"),
            "karabu": canonical_fragment("karabu"),
            "erpact": canonical_fragment("erpact", True),
        }
        t, f, v, pr = _write_tree(base, tenants, fragments, {"erpact": own})
        problems = check(t, f, v, pr)
        if problems:
            print(f"FAIL selftest: false positive on the real post-migration tree: {problems}", file=sys.stderr)
            return 1

    print(
        "OK selftest: detector fires on an added exec line, a widened glob, a "
        "missing fragment, an orphan fragment, an admins.csv fragment, an "
        "own-project grant without its AppProject, a missing own-project grant, "
        "and an AppProject that is not confined to its tenant, and stays silent "
        "on the real tree"
    )
    return 0


def main() -> int:
    if "--selftest" in sys.argv:
        return selftest()

    if not TENANTS_DIR.is_dir():
        print(f"::error::{TENANTS_DIR} not found — refusing to pass vacuously", file=sys.stderr)
        return 2
    if not FRAGMENTS_DIR.is_dir():
        print(f"::error::{FRAGMENTS_DIR} not found — refusing to pass vacuously", file=sys.stderr)
        return 2

    if not PROJECTS_DIR.is_dir():
        print(f"::error::{PROJECTS_DIR} not found — refusing to pass vacuously", file=sys.stderr)
        return 2

    problems = check(TENANTS_DIR, FRAGMENTS_DIR, VALUES_FILE, PROJECTS_DIR)
    if problems:
        for p in problems:
            print(f"::error::{p}", file=sys.stderr)
        return 1

    print("OK: tenant directories and ArgoCD RBAC fragments are 1:1 and canonical")
    return 0


if __name__ == "__main__":
    sys.exit(main())
