# Service: monteexchange
# Team: yes
# Environment: production
# Chart: base-service

image:
  repository: ghcr.io/mctlhq/monteexchange
  tag: "1.1.0"
imagePullSecrets:
  - name: ghcr-credentials
service:
  port: 8080
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env:
  APP_ENV: production
  EXCHANGE_FEE_IN_PERCENT: "2"
  WISE_HOST: https://api.transferwise.com
  WITHDRAWAL_FEE: "5"
ingress:
  enabled: true
  host: monteexchange.mctl.me
probes:
  liveness: null
  readiness: null
externalSecret:
  targetSecret: monteexchange-secrets
  data:
    - secretKey: BALANCE_ID
      remoteKey: teams/yes/monteexchange
      property: BALANCE_ID
    - secretKey: BOT_TOKEN
      remoteKey: teams/yes/monteexchange
      property: BOT_TOKEN
    - secretKey: PROFILE_ID
      remoteKey: teams/yes/monteexchange
      property: PROFILE_ID
    - secretKey: WISE_HOST
      remoteKey: teams/yes/monteexchange
      property: WISE_HOST
    - secretKey: WISE_TOKEN
      remoteKey: teams/yes/monteexchange
      property: WISE_TOKEN
    - secretKey: s
      remoteKey: teams/yes/monteexchange
      property: s
envFrom:
  - secretRef:
      name: monteexchange-secrets
