# Zero-diff import pilot for the mctl.ru zone — see mctlhq/mctl-gitops#1087.
#
# Record IDs captured from a read-only inventory on 2026-09-09. The zone serves
# only redirects to mctl.ai and carries no application traffic, which is why it
# was chosen as the first slice.
#
# Configuration for these resources is generated by the provider itself:
#   tofu plan -generate-config-out=generated.tf
# rather than being hand-written, so the imported state and the config agree by
# construction instead of by guesswork.

locals {
  zone_id = "a7ec983a32a4b15097fbb80b1f5f6924" # mctl.ru
}

import {
  to = cloudflare_dns_record.apex
  id = "${local.zone_id}/98d95445856c846ec72819617cfe3109"
}

import {
  to = cloudflare_dns_record.wildcard
  id = "${local.zone_id}/dc70fc9f9868d310840475dc32d6a425"
}

import {
  to = cloudflare_dns_record.acme_challenge
  id = "${local.zone_id}/1fa0f9f8375c95ce437061768f19d126"
}
