# mctl-api (api.mctl.ai) accepts ZITADEL tokens as a federated OIDC provider
# (mctlhq/mctl-api#434, docs/federation.md "ZITADEL" in that repository).
#
# mctl-api is a resource server only: it verifies bearer tokens and never
# runs a sign-in flow itself. What it needs from here is an audience, the
# client id of an application, which it enforces on every ZITADEL token. That
# id is generated by ZITADEL, so the Job writes the whole MCTL_OIDC_PROVIDERS
# value into mctl-api/mctl-api-oidc-zitadel, which the admins-mctl-api
# Application pre-creates and lets this Job's service account read and patch
# by name, nothing else (infra-components/mctl-platform/mctl-api/
# oidc-zitadel.yaml).
#
# Its own project, not `zitadel_project.platform`: ZITADEL puts the client
# ids of every application of a project into `aud`, so in `platform` every
# token issued to Forgejo would carry mctl-api's audience too, and Forgejo
# could replay its users' tokens against the API. A client that should call
# mctl-api is added to this project deliberately, with
# access_token_type = "OIDC_TOKEN_TYPE_JWT": mctl-api cannot verify ZITADEL's
# opaque access tokens.
#
# An API application with private-key JWT and no key issued: it has no
# credential at all, and no sign-in flow of its own. The clients that carry
# its audience are the applications of this project, today only the `mctl`
# CLI below (owner decision on mctl-api#434).

resource "zitadel_project" "mctl_api" {
  org_id = local.mctl_org_id
  name   = "MCTL API"

  # Only users of the organization that owns the project (MCTL) obtain a
  # token for it: tenant organizations are never granted it. mctl-api does
  # authenticate a ZITADEL user it has never seen (a new principal with no
  # tenant or admin access), so this keeps tenant users out until linking
  # and principal-based authorization (mctl-api#435, #377) decide otherwise.
  has_project_check = true

  lifecycle {
    precondition {
      condition     = length(data.zitadel_orgs.mctl.ids) == 1
      error_message = "Expected exactly one ZITADEL organization named \"MCTL\"."
    }
  }
}

resource "zitadel_application_api" "mctl_api" {
  org_id     = local.mctl_org_id
  project_id = zitadel_project.mctl_api.id
  name       = "mctl-api"

  auth_method_type = "API_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT"
}

# `mctl auth login --zitadel` (cli/mctl): a public client with PKCE, since a
# CLI cannot keep a secret. Loopback redirects without a port: for a native
# application ZITADEL matches a loopback redirect on path and query only
# (RFC 8252 7.3; zitadel/oidc validateAuthReqRedirectURINative), so the CLI
# listens on an ephemeral port and dev_mode stays off, which keeps every
# non-loopback http redirect refused.
#
# JWT access tokens, because mctl-api verifies tokens locally and cannot read
# ZITADEL's opaque ones. Refresh tokens so a login lasts beyond the access
# token. No role assertion: mctl-api grants nothing from ZITADEL roles until
# mctl-api#377.
resource "zitadel_application_oidc" "mctl_cli" {
  org_id     = local.mctl_org_id
  project_id = zitadel_project.mctl_api.id
  name       = "mctl-cli"

  app_type         = "OIDC_APP_TYPE_NATIVE"
  auth_method_type = "OIDC_AUTH_METHOD_TYPE_NONE"
  grant_types = [
    "OIDC_GRANT_TYPE_AUTHORIZATION_CODE",
    "OIDC_GRANT_TYPE_REFRESH_TOKEN",
  ]
  response_types = ["OIDC_RESPONSE_TYPE_CODE"]
  redirect_uris = [
    "http://127.0.0.1/callback",
    "http://localhost/callback",
  ]
  access_token_type            = "OIDC_TOKEN_TYPE_JWT"
  dev_mode                     = false
  skip_native_app_success_page = false
}

resource "kubernetes_secret_v1_data" "mctl_api_oidc" {
  metadata {
    name      = "mctl-api-oidc-zitadel"
    namespace = "mctl-api"
  }

  # The key is the env var the mctl-api chart reads (oidcProvidersSecret).
  # `name` and `issuer` are permanent: they key external_identities, so
  # changing either orphans every linked identity. audience_enforcement and
  # grant_groups stay unset: enforce, and no groups (docs/federation.md).
  data = {
    MCTL_OIDC_PROVIDERS = jsonencode([
      {
        name      = "zitadel"
        issuer    = "https://auth.mctl.ai"
        audiences = [zitadel_application_api.mctl_api.client_id]
      },
    ])
    # Not read by mctl-api (the chart references MCTL_OIDC_PROVIDERS only).
    # The CLI's client id is public by nature, but the provider marks every
    # client_id sensitive, so this Secret is where an operator reads it to
    # set the CLI default (cli/mctl/internal/auth/zitadel.go).
    MCTL_CLI_ZITADEL_CLIENT_ID = zitadel_application_oidc.mctl_cli.client_id
  }

  field_manager = "zitadel-iac"
  # Created by Argo CD with no data; see forgejo.tf.
  force = true
}
