# mctl-api (api.mctl.ai) accepts ZITADEL tokens as a federated OIDC provider
# (mctlhq/mctl-api#434, docs/federation.md "ZITADEL" in that repository).
#
# mctl-api is a resource server only: it verifies bearer tokens and never
# runs a sign-in flow itself. What it needs from here is an audience, the
# client id of an application, which it enforces on every ZITADEL token. That
# id is generated by ZITADEL, so the Job writes the whole MCTL_OIDC_PROVIDERS
# value into mctl-api/mctl-api-oidc-zitadel, which the admins-mctl-api
# Application pre-creates and lets this Job's service account read and patch
# by name, nothing else (infra-components/mctl-platform/mctl-api/
# oidc-zitadel.yaml).
#
# Its own project, not `zitadel_project.platform`: ZITADEL puts the client
# ids of every application of a project into `aud`, so in `platform` every
# token issued to Forgejo would carry mctl-api's audience too, and Forgejo
# could replay its users' tokens against the API. A client that should call
# mctl-api is added to this project deliberately, with
# access_token_type = "OIDC_TOKEN_TYPE_JWT": mctl-api cannot verify ZITADEL's
# opaque access tokens.
#
# An API application with private-key JWT and no key issued: it has no
# credential at all, and no sign-in flow of its own. Until a client joins the
# project, no token carries this audience.

resource "zitadel_project" "mctl_api" {
  org_id = local.mctl_org_id
  name   = "MCTL API"

  lifecycle {
    precondition {
      condition     = length(data.zitadel_orgs.mctl.ids) == 1
      error_message = "Expected exactly one ZITADEL organization named \"MCTL\"."
    }
  }
}

resource "zitadel_application_api" "mctl_api" {
  org_id     = local.mctl_org_id
  project_id = zitadel_project.mctl_api.id
  name       = "mctl-api"

  auth_method_type = "API_AUTH_METHOD_TYPE_PRIVATE_KEY_JWT"
}

resource "kubernetes_secret_v1_data" "mctl_api_oidc" {
  metadata {
    name      = "mctl-api-oidc-zitadel"
    namespace = "mctl-api"
  }

  # The key is the env var the mctl-api chart reads (oidcProvidersSecret).
  # `name` and `issuer` are permanent: they key external_identities, so
  # changing either orphans every linked identity. audience_enforcement and
  # grant_groups stay unset: enforce, and no groups (docs/federation.md).
  data = {
    MCTL_OIDC_PROVIDERS = jsonencode([
      {
        name      = "zitadel"
        issuer    = "https://auth.mctl.ai"
        audiences = [zitadel_application_api.mctl_api.client_id]
      },
    ])
  }

  field_manager = "zitadel-iac"
  # Created by Argo CD with no data; see forgejo.tf.
  force = true
}
