apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tenant-www
  namespace: default
  description: "Tenant WWW — namespace, quotas, and network policies"
  annotations:
    mctl.me/tenant-name: "www"
    mctl.me/github-team: "www"
    backstage.io/managed-by-location: "url:https://github.com/mctlhq/mctl-core/blob/main/platform-gitops/tenants/www/catalog-info.yaml"
    backstage.io/managed-by-origin-location: "url:https://github.com/mctlhq/mctl-core/blob/main/platform-gitops/tenants/www/catalog-info.yaml"
spec:
  type: tenant
  owner: group:default/www
  system: mctl-platform
  dependsOn: []
